// Generated by Haxe 4.2.1+bf9ff69
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		Sys._args = args;
		haxe.java.Init.init();
		haxe.root.Main.main();
	}
	
	public Main(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Main()
	{
		//line 3 "/Users/lelelo1/Projects/haxe_sample_targets/src/Main.hx"
		haxe.root.Main.__hx_ctor__Main(this);
	}
	
	
	protected static void __hx_ctor__Main(haxe.root.Main __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 5 "/Users/lelelo1/Projects/haxe_sample_targets/src/Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "hello " + haxe.root.Std.string(haxe.root.Sys.args()) ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "src/Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (5) )) )}));
	}
	
	
}


