// Generated by Haxe 4.2.1+bf9ff69
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IEquatable
{
	boolean equals(java.lang.Object to);
	
}


